POST http://localhost:3003/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjAwMXRlc3RVc2VyIiwiaWQiOiI1ZjczNjg4ZmZmZjczMzg4ZTc1M2ExNzIiLCJpYXQiOjE2MDEzOTg5NDd9.sVhczDtztcEzbq2cLzEq8S8Vjq7IXzR-DBkkdk3B2l4

{
  "content": "token testtesttest",
  "important": true
}